/*
The eXtended Keccak Code Package (XKCP)
https://github.com/XKCP/XKCP

ARMv8-A scalar+NEON hybrid x4 implementation (mlkem-native Becker-Kannwischer core).
Byte/lane helpers are generated by PlSnP-Fallback.inc (serial fallback on opt64 single).
The 24-round PermuteAll is accelerated by assembly (v8a, or v84a if __ARM_FEATURE_SHA3).

Adapted for the MQOM3 project: void* state API to match existing sponge infrastructure.
*/

#ifndef _KeccakP_1600_times4_SnP_h_
#define _KeccakP_1600_times4_SnP_h_

#include "KeccakP-1600-SnP.h"

#if defined(__ARM_FEATURE_SHA3)
#define KeccakP1600times4_implementation \
    "ARMv8.4-A scalar+NEON+SHA3 hybrid x4 (mlkem-native core)"
#else
#define KeccakP1600times4_implementation \
    "ARMv8-A scalar+NEON hybrid x4 (mlkem-native core)"
#endif

/* States are stored sequentially: stride = round_up(200, stateAlignment) = 200 (alignment=8).
 * The v8a assembly expects uint64_t[100] = 4 x 25 consecutive lanes. */
#define KeccakP1600times4_statesSizeInBytes \
    (((KeccakP1600_stateSizeInBytes + (KeccakP1600_stateAlignment-1)) \
       / KeccakP1600_stateAlignment) * KeccakP1600_stateAlignment * 4)
#define KeccakP1600times4_statesAlignment  KeccakP1600_stateAlignment

void KeccakP1600times4_StaticInitialize(void);
void KeccakP1600times4_InitializeAll(void *states);
void KeccakP1600times4_AddByte(void *states, unsigned int instanceIndex, unsigned char data, unsigned int offset);
void KeccakP1600times4_AddBytes(void *states, unsigned int instanceIndex, const unsigned char *data, unsigned int offset, unsigned int length);
void KeccakP1600times4_AddLanesAll(void *states, const unsigned char *data, unsigned int laneCount, unsigned int laneOffset);
void KeccakP1600times4_OverwriteBytes(void *states, unsigned int instanceIndex, const unsigned char *data, unsigned int offset, unsigned int length);
void KeccakP1600times4_OverwriteLanesAll(void *states, const unsigned char *data, unsigned int laneCount, unsigned int laneOffset);
void KeccakP1600times4_OverwriteWithZeroes(void *states, unsigned int instanceIndex, unsigned int byteCount);
void KeccakP1600times4_PermuteAll_4rounds(void *states);
void KeccakP1600times4_PermuteAll_6rounds(void *states);
void KeccakP1600times4_PermuteAll_12rounds(void *states);
void KeccakP1600times4_PermuteAll_24rounds(void *states);
void KeccakP1600times4_ExtractBytes(const void *states, unsigned int instanceIndex, unsigned char *data, unsigned int offset, unsigned int length);
void KeccakP1600times4_ExtractLanesAll(const void *states, unsigned char *data, unsigned int laneCount, unsigned int laneOffset);
void KeccakP1600times4_ExtractAndAddBytes(const void *states, unsigned int instanceIndex, const unsigned char *input, unsigned char *output, unsigned int offset, unsigned int length);
void KeccakP1600times4_ExtractAndAddLanesAll(const void *states, const unsigned char *input, unsigned char *output, unsigned int laneCount, unsigned int laneOffset);

size_t KeccakF1600times4_FastLoop_Absorb(void *states, unsigned int laneCount, unsigned int laneOffsetParallel, unsigned int laneOffsetSerial, const unsigned char *data, size_t dataByteLen);
size_t KeccakP1600times4_12rounds_FastLoop_Absorb(void *states, unsigned int laneCount, unsigned int laneOffsetParallel, unsigned int laneOffsetSerial, const unsigned char *data, size_t dataByteLen);

#define KeccakF1600times4_FastLoop_supported
#define KeccakP1600times4_12rounds_FastLoop_supported

#endif
